name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t sseong-web-server:latest .
          docker save sseong-web-server:latest | gzip > sseong-web-server_latest.tar.gz

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          source: sseong-web-server_latest.tar.gz
          target: /home/${{ secrets.AWS_EC2_USER }}/sseong-web-server_latest.tar.gz

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            cd /home/${{ secrets.AWS_EC2_USER }}
            gunzip sseong-web-server_latest.tar.gz
            docker load -i sseong-web-server_latest.tar
            cd /path/to/your/project
            docker-compose down
            docker-compose up -d --build
